[package]
name = "music_visualizer_1-0"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
nannou = "0.19.0"
hound = "3.4.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
